In [ ]:
import pandas as pd
import numpy as np
from faker import Faker
from datetime import datetime, timedelta
import random

In [ ]:
df = pd.read_csv('overview_data_unedited.csv', sep=";")
df.head()

,Employee_ID,First Name,Last Name,Gender,State,City,Education Level,Birthdate,Hiredate,Termdate,Department,Job Title,Salary,Performance Rating
0,00-95822412,Danielle,Johnson,Female,New York,New York City,High School,13/02/1980,16/04/2016,05/07/2021,Customer Service,Help Desk Technician,81552,Needs Improvement
1,00-42868828,John,Taylor,Male,North Carolina,Charlotte,Bachelor,22/09/1987,09/02/2017,14/06/2019,IT,System Administrator,107520,Good
2,00-83197857,Erica,Mcclain,Male,New York,New York City,Bachelor,19/05/1994,03/02/2016,06/03/2021,Operations,Logistics Coordinator,61104,Good
3,00-13999315,Brittany,Johnson,Male,New York,New York City,Bachelor,18/04/1980,06/02/2016,06/11/2018,Operations,Inventory Specialist,73770,Good
4,00-90801586,Jeffery,Wagner,Female,New York,New York City,Bachelor,07/04/1985,11/01/2015,NaN,Operations,Operations Analyst,55581,Satisfactory

In [ ]:
fake = Faker('en_US')

In [ ]:
# function to fix names in file
def generate_gendered_name(row):
    if row["Gender"].lower() == "male":
        return fake.first_name_male()
    elif row["Gender"].lower() == "female":
        return fake.first_name_female()
    else:
        return fake.first_name()  # fallback in case of missing/other

# Apply the function row by row
df["FName"] = df.apply(generate_gendered_name, axis=1)

In [ ]:
df.sample(5)

,Employee_ID,First Name,Last Name,Gender,State,City,Education Level,Birthdate,Hiredate,Termdate,Department,Job Title,Salary,Performance Rating,FName
8153,00-42706763,Kathryn,Lane,Male,Michigan,Grand Rapids,Bachelor,07/06/1993,20/09/2017,NaN,Customer Service,Customer Service Representative,65051,Good,William
3525,00-63509858,Jennifer,Scott,Female,New York,New York City,High School,01/10/1979,11/08/2017,NaN,Customer Service,Support Specialist,61727,Needs Improvement,Michelle
5892,00-90655868,Christina,Martinez,Female,New York,Rochester,Bachelor,12/02/1974,09/02/2021,NaN,Operations,Logistics Coordinator,64509,Good,Tammy
5780,00-97890289,Alyssa,Sullivan,Male,New York,New York City,Bachelor,23/04/1980,07/08/2017,NaN,Finance,Accounts Payable Specialist,65547,Excellent,Edward
6364,00-57409708,Lacey,Greene,Female,New York,Buffalo,Bachelor,17/07/1996,14/06/2017,NaN,Operations,Inventory Specialist,55288,Satisfactory,Christine

In [ ]:
df = df.rename(columns={"Last Name": "LName", "Education Level": "Education_Level", "Job Title": "Job_Title", "Performance Rating": "Performance_Rating" })

In [ ]:
df

,Employee_ID,First Name,LName,Gender,State,City,Education_Level,Birthdate,Hiredate,Termdate,Department,Job_Title,Salary,Performance_Rating,FName
0,00-95822412,Danielle,Johnson,Female,New York,New York City,High School,13/02/1980,16/04/2016,05/07/2021,Customer Service,Help Desk Technician,81552,Needs Improvement,Rebecca
1,00-42868828,John,Taylor,Male,North Carolina,Charlotte,Bachelor,22/09/1987,09/02/2017,14/06/2019,IT,System Administrator,107520,Good,Anthony
2,00-83197857,Erica,Mcclain,Male,New York,New York City,Bachelor,19/05/1994,03/02/2016,06/03/2021,Operations,Logistics Coordinator,61104,Good,Daniel
3,00-13999315,Brittany,Johnson,Male,New York,New York City,Bachelor,18/04/1980,06/02/2016,06/11/2018,Operations,Inventory Specialist,73770,Good,William
4,00-90801586,Jeffery,Wagner,Female,New York,New York City,Bachelor,07/04/1985,11/01/2015,NaN,Operations,Operations Analyst,55581,Satisfactory,Alexis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,00-29226627,Cory,Mccall,Male,New York,Buffalo,Bachelor,28/07/1969,29/05/2021,NaN,Operations,Inventory Specialist,64265,Needs Improvement,Kevin
8946,00-15091628,Brian,Nguyen,Male,New York,New York City,Bachelor,22/05/1984,06/07/2022,NaN,Operations,Inventory Specialist,63570,Excellent,Michael
8947,00-68025539,Corey,Miles,Female,Michigan,Detroit,High School,05/08/2001,03/02/2018,NaN,HR,Recruiter,73208,Needs Improvement,Hannah
8948,00-19066901,Krystal,Wilson,Male,North Carolina,Raleigh,Bachelor,23/09/1962,07/12/2023,NaN,Finance,Accountant,95028,Good,Nicholas
8949,00-50413766,Derek,Thornton,Female,New York,Rochester,PhD,04/08/1993,15/08/2017,NaN,Sales,Sales Specialist,68351,Good,Virginia

In [ ]:
# Reorder: put new first name column before last name column
cols = df.columns.tolist()
last_name_index = cols.index("LName")
cols.insert(last_name_index, cols.pop(cols.index("FName")))
df = df[cols]

In [ ]:
df = df.drop(columns=["First Name"])

In [ ]:
df.sample(5)

,Employee_ID,FName,LName,Gender,State,City,Education_Level,Birthdate,Hiredate,Termdate,Department,Job_Title,Salary,Performance_Rating
99,00-45159040,Jamie,Stewart,Female,New York,New York City,Bachelor,31/08/1984,19/10/2017,02/02/2021,IT,Software Developer,80501,Good
8479,00-81514416,Rodney,Marsh,Male,New York,Buffalo,Bachelor,30/03/1985,06/07/2016,NaN,Customer Service,Support Specialist,62655,Satisfactory
3033,00-22631766,Richard,Harrell,Male,New York,Buffalo,Bachelor,15/02/1990,17/04/2019,NaN,Sales,Sales Representative,61015,Satisfactory
7878,00-66637467,Laura,Rasmussen,Female,New York,Buffalo,Bachelor,24/12/1987,05/06/2018,NaN,Customer Service,Support Specialist,58100,Good
4753,00-95562356,Paul,Jensen,Male,Ohio,Cleveland,High School,18/08/1988,15/10/2019,NaN,Customer Service,Help Desk Technician,59187,Needs Improvement

In [ ]:
df.to_csv("overview_clean.csv", index=False)